# Numpy

------------

- It is Fundamental package for scientific Computing.
- pip install numpy ( install)
- import numpy as np (call the numpy)

# Introduction of Numpy Array

In [1]:
import numpy as np

In [14]:
# creatin 1D array
arr_1d = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr_1d) # display the arr_1d
print(type(arr_1d)) # data type
print(arr_1d.shape) # number of dimensions and its length across those dimensions
print(arr_1d.size) # Total Number of elements in the array
print(len(arr_1d))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(10,)
10
10


----

In [15]:
# creatin 2D array
arr_2d = np.array([[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]])
print(arr_2d) # display the arr_1d
print(type(arr_2d)) # data type
print(arr_2d.shape) # number of dimensions and its length across those dimensions
print(arr_2d.size) # # Total Number of elements in the array
print(len(arr_2d))

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
<class 'numpy.ndarray'>
(2, 10)
20
2


-----------

In [32]:
# creatin 3D array
arr_3d = np.array([[[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]],[[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]]])
print(arr_3d) # display the arr_1d
print(type(arr_3d)) # data type
print(arr_3d.shape) # number of dimensions(no of values in tuple) and its length across those dimensions
print(arr_3d.size) # Total Number of elements in the array
print(len(arr_3d))
print(arr_3d.ndim) # Number of dimentsions 

[[[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]

 [[0 1 2 3 4 5 6 7 8 9]
  [0 1 2 3 4 5 6 7 8 9]]]
<class 'numpy.ndarray'>
(2, 2, 10)
40
2
3


--------

In [25]:
# create an Array with Zeros
arr_zero = np.zeros((3,2))
print(arr_zero)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [26]:
# create an Array with ones
arr_ones = np.ones((3,2))
print(arr_ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [30]:
# creating an Identity matrix
iden_matrix = np.eye(4)
print(iden_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [31]:
# create an Array with a range
arr_range = np.arange(0,10,2) # start, stop, step
arr_range

array([0, 2, 4, 6, 8])

In [39]:
# indexing part of arrays

In [44]:
arr_3d = np.array([[[1,2,3],[5,6,7]],[[10,11,12],[14,15,16]]])
print(arr_3d.shape)
print(arr_3d.ndim)
print(len(arr_3d))
print(arr_3d.size)

(2, 2, 3)
3
2
12


In [42]:
arr_3d

array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[10, 11, 12],
        [14, 15, 16]]])

# Home Work

# I want to exclude 1,5,10,14, elements from this array ?

---------------------

# Boolean Indexing

In [46]:
a = np.arange(10,100,7)
print(a)

[10 17 24 31 38 45 52 59 66 73 80 87 94]


In [48]:
a[a>50]

array([52, 59, 66, 73, 80, 87, 94])

In [49]:
a[a<45]

array([10, 17, 24, 31, 38])

In [50]:

a[a<=38]

array([10, 17, 24, 31, 38])

In [51]:
a[a%2==0]

array([10, 24, 38, 52, 66, 80, 94])

---------------

# Array Operations

In [52]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)  # Element-wise
print("Division:", b / a)
print("Exponentiation:", a ** 2)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]
Exponentiation: [1 4 9]


---------------

# Aggregated Functions

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum of all elements:", np.sum(arr))
print("Sum along columns:", np.sum(arr, axis=0))  # axis = 0 Rows
print("Sum along rows:", np.sum(arr, axis=1)) # axis = 1 columns
print("Mean:", np.mean(arr))
print("Standard deviation:", np.std(arr))
print("Minimum value:", np.min(arr))
print("Maximum value:", np.max(arr))
print("Index of max value:", np.argmax(arr))

Sum of all elements: 21
Sum along columns: [5 7 9]
Sum along rows: [ 6 15]
Mean: 3.5
Standard deviation: 1.707825127659933
Minimum value: 1
Maximum value: 6
Index of max value: 5


---------------

# Broadcasting

In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Adding scalar to array
print(arr + 9)


[[10 11 12]
 [13 14 15]]


In [56]:
# Multiply array by scalar
print(arr*2)

[[ 2  4  6]
 [ 8 10 12]]


In [60]:
sarr = np.array([9,9,9])
arr+sarr

array([[10, 11, 12],
       [13, 14, 15]])

----------------

# 4. Reshaping and Combining Arrays

In [61]:
arr = np.arange(12)

# Reshape to 3x4
reshaped = arr.reshape(3, 4)
print("Reshaped array:\n", reshaped)

# Flatten array
flattened = reshaped.flatten()
print("Flattened array:", flattened)

# Transpose
transposed = reshaped.T
print("Transposed array:\n", transposed)

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


---------------

# Combining Arrays

In [62]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically
vstack = np.vstack((a, b))
print("Vertical stack:\n", vstack)

# Stack horizontally
hstack = np.hstack((a, b))
print("Horizontal stack:", hstack)

# Concatenate along axis
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated = np.concatenate((arr1, arr2), axis=0)
print("Concatenated:\n", concatenated)

Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]
Concatenated:
 [[1 2]
 [3 4]
 [5 6]]


----

# 5. Advanced Array Operations

## Universal Functions (ufuncs)

In [63]:
arr = np.array([1, 4, 9, 16, 25])

print("Square roots:", np.sqrt(arr))
print("Exponentials:", np.exp(arr))
print("Logarithms:", np.log(arr))
print("Absolute values:", np.abs(np.array([-1, -2, 3])))
print("Trigonometric functions:", np.sin(np.array([0, np.pi/2, np.pi])))

Square roots: [1. 2. 3. 4. 5.]
Exponentials: [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Logarithms: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
Absolute values: [1 2 3]
Trigonometric functions: [0.0000000e+00 1.0000000e+00 1.2246468e-16]


## Sorting

In [64]:
arr = np.array([3, 1, 4, 2, 5])

print("Sorted array:", np.sort(arr))
print("Indices that would sort:", np.argsort(arr))

# Sort 2D array
arr2d = np.array([[3, 2], [1, 4]])
print("Sorted along rows:\n", np.sort(arr2d, axis=1))
print("Sorted along columns:\n", np.sort(arr2d, axis=0))

Sorted array: [1 2 3 4 5]
Indices that would sort: [1 3 0 2 4]
Sorted along rows:
 [[2 3]
 [1 4]]
Sorted along columns:
 [[1 2]
 [3 4]]


## Filtering and Conditional Operations

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Where function
print("Where > 30:", np.where(arr > 30, arr, 0))

# Select function
conditions = [arr < 20, (arr >= 20) & (arr < 40), arr >= 40]
choices = ['low', 'medium', 'high']
print("Categorized:", np.select(conditions, choices))

---------------

# Linear Algebra Operations

In [67]:
# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Matrix product:\n", np.dot(a, b))
print("Alternative matrix product:\n", a @ b)

# Matrix inverse
mat = np.array([[1, 2], [3, 4]])
inv_mat = np.linalg.inv(mat)
print("Matrix inverse:\n", inv_mat)

# Determinant
print("Determinant:", np.linalg.det(mat))

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(mat)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Solve linear equations
# 3x + y = 9, x + 2y = 8
A = np.array([[3, 1], [1, 2]])
B = np.array([9, 8])
solution = np.linalg.solve(A, B)
print("Solution to equations:", solution)

Matrix product:
 [[19 22]
 [43 50]]
Alternative matrix product:
 [[19 22]
 [43 50]]
Matrix inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant: -2.0000000000000004
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Solution to equations: [2. 3.]


--------------

# Random Number Generation

In [68]:
# Set random seed for reproducibility
np.random.seed(42)

# Generate random numbers
print("Uniform random:", np.random.rand(5))  # 0-1
print("Normal random:", np.random.randn(5))  # standard normal

# Random integers
print("Random integers:", np.random.randint(0, 10, size=5))

# Random choice
print("Random choice:", np.random.choice(['a', 'b', 'c'], size=5))

# Shuffle array
arr = np.arange(10)
np.random.shuffle(arr)
print("Shuffled array:", arr)

Uniform random: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Normal random: [ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017]
Random integers: [5 8 0 9 2]
Random choice: ['c' 'a' 'c' 'a' 'c']
Shuffled array: [8 2 5 7 3 1 9 0 4 6]


----------------

# Working with Missing Data

In [69]:
# Create array with missing values
arr = np.array([1, 2, np.nan, 4, 5])

print("Array with NaN:", arr)
print("Is NaN:", np.isnan(arr))
print("Sum ignoring NaN:", np.nansum(arr))
print("Mean ignoring NaN:", np.nanmean(arr))

# Replace NaN with 0
arr[np.isnan(arr)] = 0
print("Array after replacement:", arr)

Array with NaN: [ 1.  2. nan  4.  5.]
Is NaN: [False False  True False False]
Sum ignoring NaN: 12.0
Mean ignoring NaN: 3.0
Array after replacement: [1. 2. 0. 4. 5.]


---------

# Vectorized Operations

In [70]:
# Traditional Python approach (slow)
def python_square(numbers):
    result = []
    for num in numbers:
        result.append(num ** 2)
    return result

# NumPy vectorized approach (fast)
def numpy_square(numbers):
    return numbers ** 2

# Compare performance
large_array = np.arange(1_000_000)

%timeit python_square(large_array)  # Much slower
%timeit numpy_square(large_array)   # Much faster

172 ms ± 474 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.76 ms ± 340 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


----------------

# Saving and Loading Arrays

In [71]:
# Create array to save
arr = np.arange(10).reshape(2, 5)

# Save to binary file
np.save('my_array.npy', arr)

# Load from binary file
loaded_arr = np.load('my_array.npy')
print("Loaded array:\n", loaded_arr)

# Save to text file
np.savetxt('my_array.txt', arr)

# Load from text file
loaded_txt = np.loadtxt('my_array.txt')
print("Loaded from text:\n", loaded_txt)

Loaded array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Loaded from text:
 [[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


-----------

# Practical Data Analysis Example

In [73]:
# Load dataset (example: student scores)
scores = np.array([
    [80, 85, 90],  # student 1
    [75, 92, 88],   # student 2
    [90, 78, 85],   # student 3
    [85, 88, 92]    # student 4
])

# Calculate average score per student
print("Average scores:", np.mean(scores, axis=1))

# Find students with average > 85
good_students = np.mean(scores, axis=1) > 85
print("Good students:\n", scores[good_students])

# Normalize scores (scale to 0-1)
normalized = (scores - np.min(scores)) / (np.max(scores) - np.min(scores))
print("Normalized scores:\n", normalized)

# Calculate correlation between subjects
correlation = np.corrcoef(scores.T)  # Transpose to correlate subjects
print("Correlation matrix:\n", correlation)

Average scores: [85.         85.         84.33333333 88.33333333]
Good students:
 [[85 88 92]]
Normalized scores:
 [[0.29411765 0.58823529 0.88235294]
 [0.         1.         0.76470588]
 [0.88235294 0.17647059 0.58823529]
 [0.58823529 0.76470588 1.        ]]
Correlation matrix:
 [[ 1.         -0.85206474 -0.30263639]
 [-0.85206474  1.          0.58090647]
 [-0.30263639  0.58090647  1.        ]]
